import { useMemo, useState, useEffect } from 'react';
import { Link, NavLink, Route, Routes, useParams } from 'react-router-dom';
import { AnimatePresence, motion, useReducedMotion } from 'framer-motion';
import { ArrowDownRight, ArrowRight, Bike, Box, CircleCheck, Factory, Globe2, Hammer, Mail, Menu, MessageCircle, ShieldCheck, Sparkles, Truck, X } from 'lucide-react';

const contact = { phone: '+92 342 7189884', email: 'skylineglobalindustries@gmail.com', location: 'Sialkot, Punjab, Pakistan' };

// These are the verified Cloudinary assets in the `products` folder.
// Most are PNG; two catalogue assets are JPG.
const cloudinary = (code: string) => {
  const extension = code === 'SLGI-RAG-06' || code === 'SLGI-CG-08' ? 'jpg' : 'png';
  return `https://res.cloudinary.com/m2w7btvw/image/upload/f_auto,q_auto/${code}.${extension}`;
};

const categories = [
  { slug: 'motorbike-gloves', name: 'MotorBike Gloves', prefix: 'SLGI-MG', count: 12, icon: Bike, art: 'motorbike', image: 'SLGI-MG-01' },
  { slug: 'rugby-gloves', name: 'Rugby Gloves', prefix: 'SLGI-RAG', count: 8, icon: ShieldCheck, art: 'rugby', image: 'SLGI-RAG-01' },
  { slug: 'golf-gloves', name: 'Golf Gloves', prefix: 'SLGI-GG', count: 8, icon: Sparkles, art: 'golf', image: 'SLGI-GG-01' },
  { slug: 'fitness-gloves', name: 'Fitness Gloves', prefix: 'SLGI-FG', count: 8, icon: Hammer, art: 'fitness', image: 'SLGI-FG-01' },
  { slug: 'cycling-gloves', name: 'Cycling Gloves', prefix: 'SLGI-CG', count: 8, icon: Bike, art: 'cycling', image: 'SLGI-CG-01' },
  { slug: 'tactical-gloves', name: 'Tactical Gloves', prefix: 'SLGI-TG', count: 8, icon: ShieldCheck, art: 'tactical', image: 'SLGI-TG-01' },
] as const;

type Product = { slug: string; code: string; category: string; categoryName: string; index: number };
const products: Product[] = categories.flatMap((category) => Array.from({ length: category.count }, (_, index) => ({
  slug: `${category.slug}-${String(index + 1).padStart(2, '0')}`,
  code: `${category.prefix}-${String(index + 1).padStart(2, '0')}`,
  category: category.slug,
  categoryName: category.name,
  index: index + 1,
})));

const nav = [['/about', 'About'], ['/products', 'Products'], ['/oem-private-label', 'OEM / Private Label'], ['/manufacturing', 'Manufacturing'], ['/quality', 'Quality'], ['/gallery', 'Gallery'], ['/contact', 'Contact']];
const reveal = { hidden: { opacity: 0, y: 28 }, show: { opacity: 1, y: 0, transition: { duration: .65, ease: [0.22, 1, .36, 1] } } };

export default function App() {
  return <SiteShell><AnimatePresence mode="wait"><Routes>
    <Route path="/" element={<Home />} /><Route path="/about" element={<About />} /><Route path="/products" element={<Products />} />
    <Route path="/products/:category" element={<Products />} /><Route path="/products/:category/:slug" element={<ProductDetail />} />
    <Route path="/oem-private-label" element={<OEM />} /><Route path="/manufacturing" element={<Manufacturing />} /><Route path="/quality" element={<Quality />} />
    <Route path="/credentials" element={<Credentials />} /><Route path="/gallery" element={<Gallery />} /><Route path="/contact" element={<Contact />} /><Route path="*" element={<NotFound />} />
  </Routes></AnimatePresence></SiteShell>;
}

function SiteShell({ children }: { children: React.ReactNode }) {
  const [open, setOpen] = useState(false);
  return <div className="site"><header className="header"><div className="container nav">
    <Link className="brand" to="/" onClick={() => setOpen(false)}><img src="/images/logo.svg" alt="Skyline Global Industries" /><span><strong>SKYLINE</strong><small>GLOBAL INDUSTRIES</small></span></Link>
    <nav className="desktopNav">{nav.map(([href, label]) => <NavLink key={href} to={href}>{label}</NavLink>)}</nav>
    <Link className="quoteBtn navQuote" to="/contact">Request a Quote <ArrowRight size={15}/></Link>
    <button className="menuBtn" onClick={() => setOpen(v => !v)} aria-label="Menu">{open ? <X/> : <Menu/>}</button>
  </div>{open && <motion.nav className="mobileNav" initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}}>{nav.map(([href,label]) => <Link key={href} to={href} onClick={() => setOpen(false)}>{label}</Link>)}<Link className="quoteBtn" to="/contact" onClick={() => setOpen(false)}>Request a Quote <ArrowRight size={15}/></Link></motion.nav>}</header><main>{children}</main><Footer/></div>;
}

function Footer(){ return <footer className="footer"><div className="container footerGrid"><div><img className="footerLogo" src="/images/logo.svg" alt="Skyline Global Industries"/><p>Manufacturers and exporters of premium quality gloves from Sialkot, Pakistan.</p></div><div><span>EXPLORE</span><Link to="/products">Product Catalogue</Link><Link to="/oem-private-label">OEM / Private Label</Link><Link to="/manufacturing">Manufacturing</Link><Link to="/quality">Quality</Link></div><div><span>COMPANY</span><Link to="/about">About Skyline</Link><Link to="/credentials">Company Credentials</Link><Link to="/gallery">Gallery</Link><Link to="/contact">Contact</Link></div><div><span>CONTACT</span><a href={`tel:${contact.phone}`}>{contact.phone}</a><a href={`mailto:${contact.email}`}>{contact.email}</a><small>{contact.location}</small></div></div><div className="container footerBottom"><span>© 2026 Skyline Global Industries</span><span>Sialkot · Pakistan</span></div></footer> }

function Home(){ const reduce=useReducedMotion(); return <>
  <section className="heroCatalog"><div className="heroBlob one"/><div className="heroBlob two"/><div className="container heroCatalogGrid">
    <motion.div className="heroCatalogCopy" variants={reveal} initial="hidden" animate="show"><div className="eyebrow">SIALKOT · PAKISTAN</div><h1>MANUFACTURERS &<br/>EXPORTERS OF<br/><em>PREMIUM QUALITY</em><br/><strong>GLOVES</strong></h1><p>OEM, private-label and custom glove manufacturing for brands, wholesalers, distributors and importers.</p><div className="heroActions"><Link className="quoteBtn" to="/products">Explore Catalogue <ArrowRight size={16}/></Link><Link className="outlineBtn" to="/contact">Start an Enquiry</Link></div><div className="contactStrip"><a href={`tel:${contact.phone}`}><MessageCircle size={16}/>{contact.phone}</a><a href={`mailto:${contact.email}`}><Mail size={16}/>{contact.email}</a><span><Globe2 size={16}/>{contact.location}</span></div></motion.div>
    <motion.div className="heroCatalogArt" initial={reduce?false:{opacity:0,scale:.88,x:30}} animate={reduce?undefined:{opacity:1,scale:1,x:0}} transition={{duration:1,ease:[.16,1,.3,1]}}><div className="worldDisc"/><div className="heroProductCollage">{['SLGI-MG-01','SLGI-GG-01','SLGI-TG-01','SLGI-FG-01','SLGI-RAG-01'].map((code,i)=><img key={code} className={`heroProduct p${i+1}`} src={cloudinary(code)} alt="Skyline premium glove" />)}</div><div className="heroTag">SKYLINE / 01</div></motion.div>
  </div><div className="catalogCurve"><span>OEM & PRIVATE LABEL</span><span>QUALITY CONTROL</span><span>GLOBAL B2B SUPPLY</span><Link to="/about">DISCOVER SKYLINE <ArrowDownRight size={14}/></Link></div></section>
  <SectionIntro eyebrow="THE SKYLINE APPROACH" title="Built in Sialkot. Ready for global buyers." copy="Skyline Global Industries is positioned as a glove manufacturing and export partner focused on craftsmanship, modern production, quality control and dependable B2B service." link="About the company" to="/about"/>
  <section className="section catalogSection"><div className="container"><SectionHeader eyebrow="PRODUCT COLLECTION" title="Six focused glove categories." link="View full catalogue" to="/products"/><div className="categoryGrid">{categories.map((c,i)=><CategoryCard key={c.slug} category={c} index={i}/>)}</div></div></section>
  <section className="oemBand"><div className="container oemBandGrid"><div><div className="eyebrow light">OEM & PRIVATE LABEL</div><h2>Your brand.<br/><em>Our manufacturing.</em></h2><p>From product development to final packaging, we provide complete OEM and private-label support tailored to your brand.</p><Link className="lightBtn" to="/oem-private-label">Explore OEM capabilities <ArrowRight size={16}/></Link></div><div className="oemRealVisual"><img className="oemProductPhoto" src={cloudinary('SLGI-TG-01')} alt="Skyline tactical glove"/><div className="oemPackageMock">YOUR<br/>BRAND<br/><Box size={34}/></div></div></div></section>
  <section className="section commitment"><div className="container"><div className="commitGrid"><motion.div variants={reveal} initial="hidden" whileInView="show" viewport={{once:true}}><div className="eyebrow">WHY BUYERS WORK WITH US</div><h2>Quality is built into the process.</h2><p>Our company material emphasizes skilled craftsmanship, modern machinery, strict quality control, competitive factory pricing and on-time delivery.</p><Link className="textLink" to="/quality">Our quality approach <ArrowRight size={15}/></Link></motion.div><div className="principleGrid">{[['01',Factory,'Skilled craftsmanship'],['02',ShieldCheck,'Quality control'],['03',Truck,'On-time delivery'],['04',Globe2,'Global B2B focus']].map(([n,I,t])=><motion.div key={n as string} variants={reveal} initial="hidden" whileInView="show" viewport={{once:true}}><b>{n as string}</b><I size={22}/><strong>{t as string}</strong></motion.div>)}</div></div></div></section>
  <CTA/>
</> }

function SectionIntro({eyebrow,title,copy,link,to}:{eyebrow:string;title:string;copy:string;link:string;to:string}){return <section className="section intro"><div className="container introGrid"><div><div className="eyebrow">{eyebrow}</div><h2>{title}</h2></div><div><p>{copy}</p><Link className="textLink" to={to}>{link}<ArrowRight size={15}/></Link></div></div></section>}
function SectionHeader({eyebrow,title,link,to}:{eyebrow:string;title:string;link:string;to:string}){return <div className="sectionHeader"><div><div className="eyebrow">{eyebrow}</div><h2>{title}</h2></div><Link className="textLink" to={to}>{link}<ArrowRight size={15}/></Link></div>}
function CategoryCard({category,index}:{category:(typeof categories)[number];index:number}){const Icon=category.icon;return <Link className="categoryCard" to={`/products/${category.slug}`}><div className={`categoryArt art-${category.art}`}><img src={cloudinary(category.image)} alt={category.name}/><div className="artRing"/><Icon size={28}/><span>0{index+1}</span></div><div className="categoryInfo"><div><small>{category.prefix}</small><h3>{category.name}</h3><p>Confirmed catalogue category for B2B sourcing.</p></div><ArrowRight size={18}/></div></Link>}
function PageHero({eyebrow,title,copy}:{eyebrow:string;title:string;copy?:string}){return <section className="pageHero"><div className="container"><div className="eyebrow">{eyebrow}</div><h1>{title}</h1>{copy&&<p>{copy}</p>}</div></section>}

function Products(){const {category}=useParams(); const [filter,setFilter]=useState(category??'all'); useEffect(()=>{setFilter(category??'all')},[category]); const visible=useMemo(()=>filter==='all'?products:products.filter(p=>p.category===filter),[filter]);return <><PageHero eyebrow="PRODUCT CATALOGUE" title="A visual range built for faster sourcing." copy="Browse the confirmed launch categories and SKU references. Technical specifications are only shown where supplied by the source catalogue."/><section className="section products"><div className="container"><div className="filterBar"><button className={filter==='all'?'selected':''} onClick={()=>setFilter('all')}>All <b>{products.length}</b></button>{categories.map(c=><button key={c.slug} className={filter===c.slug?'selected':''} onClick={()=>setFilter(c.slug)}>{c.name}</button>)}</div><div className="catalogMeta"><span>{visible.length} references</span><span>SKU-led · OEM enquiries welcome</span></div><div className="productGrid">{visible.map((p,i)=><ProductCard key={p.slug} product={p} index={i}/>)}</div></div></section></>}
function ProductCard({product,index}:{product:Product;index:number}){return <motion.div initial={{opacity:0,y:18}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{duration:.4,delay:Math.min(index*.02,.12)}}><Link className="productCard" to={`/products/${product.category}/${product.slug}`}><div className="productVisual"><img src={cloudinary(product.code)} alt={product.code}/><span>{product.code}</span><i>VIEW <ArrowRight size={12}/></i></div><div className="productMeta"><small>{product.categoryName}</small><strong>{product.code}</strong><ArrowRight size={16}/></div></Link></motion.div>}
function ProductDetail(){const {category,slug}=useParams();const product=products.find(p=>p.category===category&&p.slug===slug);if(!product)return <NotFound/>;return <><PageHero eyebrow={product.categoryName.toUpperCase()} title={product.code} copy="Product reference from the confirmed launch catalogue."/><section className="section detail"><div className="container detailGrid"><div className="detailArt"><img src={cloudinary(product.code)} alt={product.code}/></div><div><div className="eyebrow">PRODUCT REFERENCE</div><h2>{product.code}</h2><div className="detailRows"><div><span>Category</span><b>{product.categoryName}</b></div><div><span>Product code</span><b>{product.code}</b></div><div><span>Supply model</span><b>OEM / B2B</b></div></div><p className="sourceNote">Materials, sizes, colours, applications and individual MOQ are not published because they were not supplied in the source catalogue.</p><Link className="quoteBtn" to={`/contact?product=${encodeURIComponent(product.code)}`}>Request a Quote <ArrowRight size={16}/></Link></div></div></section></>}

function About(){return <><PageHero eyebrow="ABOUT SKYLINE" title="A Sialkot manufacturing partner built for global business." copy="Skyline Global Industries manufactures and exports premium-quality gloves, with a focus on OEM manufacturing, private labeling and custom glove solutions."/><section className="section aboutFeature"><div className="container aboutGrid"><div className="aboutVisual"><div className="aboutCircle"/><div className="aboutPhotoFrame"><img src={cloudinary('SLGI-FG-01')} alt="Skyline glove manufacturing product"/></div><span>SIALKOT / PAKISTAN</span></div><div><div className="eyebrow">WHO WE ARE</div><h2>Manufacturing with a buyer-first mindset.</h2><p>Based in Sialkot, Pakistan, Skyline serves brands, wholesalers, distributors and importers looking for a dependable glove manufacturing partner.</p><p>The supplied company material positions the business around skilled craftsmanship, modern production technology, strict quality control, competitive factory pricing and on-time delivery.</p><div className="points"><div><CircleCheck size={19}/><span>Skilled craftsmanship</span></div><div><CircleCheck size={19}/><span>Modern production technology</span></div><div><CircleCheck size={19}/><span>Strict quality control</span></div><div><CircleCheck size={19}/><span>Competitive factory pricing</span></div></div></div></div></section></> }
function OEM(){return <><PageHero eyebrow="OEM / PRIVATE LABEL" title="Turn a product brief into your branded glove range." copy="OEM and private-label support for brands, distributors and importers."/><section className="section"><div className="container split"><div><div className="eyebrow">CAPABILITY</div><h2>From concept to packed shipment.</h2><p>Discuss product direction, materials, colours, branding, packaging and export requirements with the Skyline team.</p><Link className="quoteBtn" to="/contact">Start an OEM enquiry <ArrowRight size={16}/></Link></div><div className="oemPageVisual"><img src={cloudinary('SLGI-TG-01')} alt="OEM glove reference"/></div></div></section></>}
function Manufacturing(){return <><PageHero eyebrow="MANUFACTURING" title="Production designed around consistency." copy="Skilled workmanship, modern production technology and quality control support dependable B2B supply."/><section className="section"><div className="container processGrid">{[['01','CUT','Material preparation and cutting'],['02','BUILD','Skilled assembly and stitching'],['03','CONTROL','Inspection and quality checks'],['04','PACK','Packing and export readiness']].map(([n,t,c])=><div className="processCard" key={n}><b>{n}</b><h3>{t}</h3><p>{c}</p></div>)}</div></section></>}
function Quality(){return <><PageHero eyebrow="QUALITY" title="Quality control at every stage." copy="Our quality positioning is built around inspection, consistency and dependable export supply."/><section className="section"><div className="container qualityGrid"><div><div className="eyebrow">QUALITY SYSTEM</div><h2>Built for buyer confidence.</h2><p>Every production programme should be aligned around agreed specifications, inspection points and final packing checks.</p></div><div className="qualityCards">{['Incoming material checks','In-process inspection','Final product inspection','Packing verification'].map((x,i)=><div key={x}><b>0{i+1}</b><span>{x}</span></div>)}</div></div></section></>}
function Credentials(){return <><PageHero eyebrow="COMPANY CREDENTIALS" title="A manufacturing profile buyers can evaluate."/><section className="section"><div className="container credentialGrid">{[['01','SIALKOT BASED','Manufacturing and export operations in Sialkot, Pakistan.'],['02','B2B FOCUS','Serving brands, wholesalers, distributors and importers.'],['03','OEM READY','Private-label and custom glove manufacturing support.']].map(([n,t,c])=><div key={n}><b>{n}</b><h3>{t}</h3><p>{c}</p></div>)}</div></section></>}
function Gallery(){const images=['SLGI-MG-01','SLGI-RAG-01','SLGI-GG-01','SLGI-FG-01','SLGI-CG-01','SLGI-TG-01','SLGI-MG-07','SLGI-TG-04'];return <><PageHero eyebrow="VISUAL CATALOGUE" title="A closer look at the Skyline range." copy="Selected product references from the current launch catalogue."/><section className="section"><div className="container galleryGrid">{images.map(code=><div className="galleryItem" key={code}><img src={cloudinary(code)} alt={code}/><span>{code}</span></div>)}</div></section></>}
function Contact(){return <><PageHero eyebrow="CONTACT" title="Tell us what you need to manufacture." copy="Send your product, branding and sourcing requirements to the Skyline team."/><section className="section"><div className="container contactGrid"><div><div className="eyebrow">DIRECT</div><h2>Start a B2B conversation.</h2><p>For OEM, private-label and catalogue enquiries, contact Skyline directly.</p><a className="quoteBtn" href={`mailto:${contact.email}`}>Email Skyline <ArrowRight size={16}/></a></div><div className="contactCard"><strong>{contact.email}</strong><span>{contact.phone}</span><span>{contact.location}</span></div></div></section></>}
function CTA(){return <section className="cta"><div className="container"><div><div className="eyebrow light">READY TO SOURCE?</div><h2>Build your next glove range with Skyline.</h2></div><Link className="lightBtn" to="/contact">Request a Quote <ArrowRight size={16}/></Link></div></section>}
function NotFound(){return <section className="section"><div className="container"><div className="eyebrow">404</div><h1>Page not found.</h1><Link className="quoteBtn" to="/">Return home <ArrowRight size={16}/></Link></div></section>}
