import { useMemo, useState, useEffect } from 'react';
import { Link, NavLink, Route, Routes, useParams, useSearchParams } from 'react-router-dom';
import { AnimatePresence, motion, useReducedMotion } from 'framer-motion';
import { ArrowDownRight, ArrowRight, Bike, Box, CircleCheck, Factory, Globe2, Hammer, Menu, ShieldCheck, Sparkles, Truck, X } from 'lucide-react';
import './footer-socials.css';

const contact = { phone: '+92 342 7189884', email: 'skylineglobalindustries@gmail.com', location: 'Sialkot, Punjab, Pakistan' };
const FORMSPREE_ENDPOINT = 'https://formspree.io/f/xoeankkr';
const whatsappUrl = 'https://wa.me/923427189884?text=Hello%20Skyline%20Global%20Industries%2C%20I%27d%20like%20to%20discuss%20a%20glove%20sourcing%20requirement.';
const exactHeaderLogo = 'https://res.cloudinary.com/m2w7btvw/image/upload/v1786908840/skyline/skyline/header-exact-logo.webp';

const cloudinary = (code: string) => {
  const extension = code === 'SLGI-RAG-06' || code === 'SLGI-CG-08' ? 'jpg' : 'png';
  return `https://res.cloudinary.com/m2w7btvw/image/upload/f_auto,q_auto/${code}.${extension}`;
};

const categories = [
  { slug: 'motorbike-gloves', name: 'MotorBike Gloves', prefix: 'SLGI-MG', count: 12, icon: Bike, art: 'motorbike', image: 'SLGI-MG-01' },
  { slug: 'rugby-gloves', name: 'Rugby Gloves', prefix: 'SLGI-RAG', count: 8, icon: ShieldCheck, art: 'rugby', image: 'SLGI-RAG-01' },
  { slug: 'golf-gloves', name: 'Golf Gloves', prefix: 'SLGI-GG', count: 8, icon: Sparkles, art: 'golf', image: 'SLGI-GG-01' },
  { slug: 'fitness-gloves', name: 'Fitness Gloves', prefix: 'SLGI-FG', count: 8, icon: Hammer, art: 'fitness', image: 'SLGI-FG-01' },
  { slug: 'cycling-gloves', name: 'Cycling Gloves', prefix: 'SLGI-CG', count: 8, icon: Bike, art: 'cycling', image: 'SLGI-CG-01' },
  { slug: 'tactical-gloves', name: 'Tactical Gloves', prefix: 'SLGI-TG', count: 8, icon: ShieldCheck, art: 'tactical', image: 'SLGI-TG-01' },
] as const;

type Product = { slug: string; code: string; category: string; categoryName: string; index: number };
const products: Product[] = categories.flatMap((category) => Array.from({ length: category.count }, (_, index) => ({
  slug: `${category.slug}-${String(index + 1).padStart(2, '0')}`,
  code: `${category.prefix}-${String(index + 1).padStart(2, '0')}`,
  category: category.slug,
  categoryName: category.name,
  index: index + 1,
})));

const nav = [['/about', 'About'], ['/products', 'Products'], ['/oem-private-label', 'OEM / Private Label'], ['/manufacturing', 'Manufacturing'], ['/quality', 'Quality'], ['/gallery', 'Gallery'], ['/contact', 'Contact']];
const reveal = { hidden: { opacity: 0, y: 28 }, show: { opacity: 1, y: 0, transition: { duration: .65, ease: [0.22, 1, .36, 1] } } };

export default function App() {
  return <SiteShell><AnimatePresence mode="wait"><Routes>
    <Route path="/" element={<Home />} /><Route path="/about" element={<About />} /><Route path="/products" element={<Products />} />
    <Route path="/products/:category" element={<Products />} /><Route path="/products/:category/:slug" element={<ProductDetail />} />
    <Route path="/oem-private-label" element={<OEM />} /><Route path="/manufacturing" element={<Manufacturing />} /><Route path="/quality" element={<Quality />} />
    <Route path="/credentials" element={<Credentials />} /><Route path="/gallery" element={<Gallery />} /><Route path="/contact" element={<Contact />} /><Route path="*" element={<NotFound />} />
  </Routes></AnimatePresence></SiteShell>;
}

function SiteShell({ children }: { children: React.ReactNode }) {
  const [open, setOpen] = useState(false);
  return <div className="site"><header className="header"><div className="container nav">
    <Link className="brand" to="/" onClick={() => setOpen(false)}><img src={exactHeaderLogo} alt="Skyline Global Industries" /></Link>
    <nav className="desktopNav">{nav.map(([href, label]) => <NavLink key={href} to={href}>{label}</NavLink>)}</nav>
    <Link className="quoteBtn navQuote" to="/contact">Request a Quote <ArrowRight size={15}/></Link>
    <button className="menuBtn" onClick={() => setOpen(v => !v)} aria-label="Menu">{open ? <X/> : <Menu/>}</button>
  </div>{open && <motion.nav className="mobileNav" initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}}>{nav.map(([href,label]) => <Link key={href} to={href} onClick={() => setOpen(false)}>{label}</Link>)}<Link className="quoteBtn" to="/contact" onClick={() => setOpen(false)}>Request a Quote <ArrowRight size={15}/></Link></motion.nav>}</header><main>{children}</main><Footer/></div>;
}

function InstagramIcon(){return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r=".8" fill="currentColor" stroke="none"/></svg>}
function FacebookIcon(){return <svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M14 8h3V4h-3c-3.1 0-5 1.9-5 5v3H6v4h3v4h4v-4h3l1-4h-4V9c0-.7.3-1 1-1Z"/></svg>}
function TikTokIcon(){return <svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M15.5 3c.3 1.9 1.4 3.2 3.5 3.5v3.1c-1.5-.1-2.7-.6-3.7-1.4v6.3c0 4-2.6 6.5-6.2 6.5A5.9 5.9 0 1 1 9 9.2v3.3a2.8 2.8 0 1 0 2.9 2.7V3h3.6Z"/></svg>}
function WhatsAppIcon(){return <svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M12 2.5a9.5 9.5 0 0 0-8.16 14.37L2.5 21.5l4.78-1.31A9.5 9.5 0 1 0 12 2.5Zm0 17.3a7.78 7.78 0 0 1-3.96-1.08l-.28-.17-2.84.78.76-2.77-.18-.29A7.8 7.8 0 1 1 12 19.8Zm4.27-5.83c-.23-.12-1.34-.66-1.55-.74-.21-.08-.36-.12-.51.12-.15.23-.59.74-.72.89-.13.16-.26.17-.49.06-.23-.12-.96-.35-1.83-1.1-.68-.59-1.14-1.31-1.27-1.53-.13-.23-.01-.35.1-.46.1-.1.23-.26.35-.39.12-.13.15-.23.23-.39.08-.16.04-.29-.02-.41-.06-.12-.51-1.23-.7-1.68-.18-.44-.37-.38-.51-.39h-.43c-.15 0-.39.06-.6.29-.21.23-.78.76-.78 1.86s.8 2.16.91 2.31c.12.16 1.56 2.39 3.78 3.35.53.23.94.37 1.26.47.53.17 1.01.15 1.39.09.42-.06 1.34-.55 1.53-1.08.19-.53.19-.98.13-1.08-.06-.1-.21-.16-.44-.28Z"/></svg>}
function GmailIcon(){return <svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M3.5 6.5 12 13l8.5-6.5v11.2a1.8 1.8 0 0 1-1.8 1.8H5.3a1.8 1.8 0 0 1-1.8-1.8V6.5Z" fill="currentColor" opacity=".18"/><path d="M3.5 6.5 12 13l8.5-6.5" stroke="currentColor" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round"/><path d="M3.5 17.7V6.8A1.8 1.8 0 0 1 6.4 5.35L12 9.6l5.6-4.25a1.8 1.8 0 0 1 2.9 1.45v10.9" stroke="currentColor" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round"/></svg>}

function Footer(){ return <footer className="footer"><div className="container footerGrid"><div><img className="footerLogo" src="/images/logo.svg" alt="Skyline Global Industries"/><p>Manufacturers and exporters of premium quality gloves from Sialkot, Pakistan.</p><div className="footerSocialsLabel">CONNECT WITH SKYLINE</div><div id="skyline-footer-socials" className="skylineFooterSocials" data-skyline-socials="primary">
  <a className="skylineFooterSocialLink instagram" href="https://www.instagram.com/skylineglobalindustries?igsh=MWkwNDlycHdtdXVleg==" target="_blank" rel="noopener noreferrer" aria-label="Skyline Global Industries on Instagram"><InstagramIcon/></a>
  <a className="skylineFooterSocialLink facebook" href="https://www.facebook.com/share/1JWWj4JrJC/" target="_blank" rel="noopener noreferrer" aria-label="Skyline Global Industries on Facebook"><FacebookIcon/></a>
  <a className="skylineFooterSocialLink tiktok" href="https://www.tiktok.com/@skylineglobalindustries" target="_blank" rel="noopener noreferrer" aria-label="Skyline Global Industries on TikTok"><TikTokIcon/></a>
  <a className="skylineFooterSocialLink whatsapp" href={whatsappUrl} target="_blank" rel="noopener noreferrer" aria-label="Contact Skyline Global Industries on WhatsApp"><WhatsAppIcon/></a>
  <a className="skylineFooterSocialLink gmail" href={`mailto:${contact.email}`} aria-label="Email Skyline Global Industries"><GmailIcon/></a>
</div></div><div><span>EXPLORE</span><Link to="/products">Product Catalogue</Link><Link to="/oem-private-label">OEM / Private Label</Link><Link to="/manufacturing">Manufacturing</Link><Link to="/quality">Quality</Link></div><div><span>COMPANY</span><Link to="/about">About Skyline</Link><Link to="/credentials">Company Credentials</Link><Link to="/gallery">Gallery</Link><Link to="/contact">Contact</Link></div><div><span>CONTACT</span><a href={`tel:${contact.phone}`}>{contact.phone}</a><a href={`mailto:${contact.email}`}>{contact.email}</a><small>{contact.location}</small></div></div><div className="container footerBottom"><span>© 2026 Skyline Global Industries</span><span>Sialkot · Pakistan</span></div></footer> }

function Home(){ const reduce=useReducedMotion(); return <>
  <section className="heroCatalog"><div className="heroBlob one"/><div className="heroBlob two"/><div className="container heroCatalogGrid">
    <motion.div className="heroCatalogCopy" variants={reveal} initial="hidden" animate="show"><div className="eyebrow">SIALKOT · PAKISTAN</div><h1>MANUFACTURERS &<br/>EXPORTERS OF<br/><em>PREMIUM QUALITY</em><br/><strong>GLOVES</strong></h1><p>OEM, private-label and custom glove manufacturing for brands, wholesalers, distributors and importers.</p><div className="heroActions"><Link className="quoteBtn" to="/products">Explore Catalogue <ArrowRight size={16}/></Link><Link className="outlineBtn" to="/contact">Start an Enquiry</Link></div><div className="contactStrip"><a href={`tel:${contact.phone}`}>{contact.phone}</a><a href={`mailto:${contact.email}`}>{contact.email}</a><span><Globe2 size={16}/>{contact.location}</span></div></motion.div>
    <motion.div className="heroCatalogArt" initial={reduce?false:{opacity:0,scale:.88,x:30}} animate={reduce?undefined:{opacity:1,scale:1,x:0}} transition={{duration:1,ease:[.16,1,.3,1]}}><div className="worldDisc"/><div className="heroProductCollage">{['SLGI-MG-01','SLGI-GG-01','SLGI-TG-01','SLGI-FG-01','SLGI-RAG-01'].map((code,i)=><img key={code} className={`heroProduct p${i+1}`} src={cloudinary(code)} alt="Skyline premium glove" />)}</div><div className="heroTag">SKYLINE / 01</div></motion.div>
  </div><div className="catalogCurve"><span>OEM & PRIVATE LABEL</span><span>QUALITY CONTROL</span><span>GLOBAL B2B SUPPLY</span><Link to="/about">DISCOVER SKYLINE <ArrowDownRight size={14}/></Link></div></section>
  <SectionIntro eyebrow="THE SKYLINE APPROACH" title="Built in Sialkot. Ready for global buyers." copy="Skyline Global Industries is positioned as a glove manufacturing and export partner focused on craftsmanship, modern production, quality control and dependable B2B service." link="About the company" to="/about"/>
  <section className="section catalogSection"><div className="container"><SectionHeader eyebrow="PRODUCT COLLECTION" title="Six focused glove categories." link="View full catalogue" to="/products"/><div className="categoryGrid">{categories.map((c,i)=><CategoryCard key={c.slug} category={c} index={i}/>)}</div></div></section>
  <section className="oemBand"><div className="container oemBandGrid"><div><div className="eyebrow light">OEM & PRIVATE LABEL</div><h2>Your brand.<br/><em>Our manufacturing.</em></h2><p>From product development to final packaging, we provide complete OEM and private-label support tailored to your brand.</p><Link className="lightBtn" to="/oem-private-label">Explore OEM capabilities <ArrowRight size={16}/></Link></div><div className="oemRealVisual"><img className="oemProductPhoto" src={cloudinary('SLGI-TG-01')} alt="Skyline tactical glove"/><div className="oemPackageMock">YOUR<br/>BRAND<br/><Box size={34}/></div></div></div></section>
  <section className="section commitment"><div className="container"><div className="commitGrid"><motion.div variants={reveal} initial="hidden" whileInView="show" viewport={{once:true}}><div className="eyebrow">WHY BUYERS WORK WITH US</div><h2>Quality is built into the process.</h2><p>Our company material emphasizes skilled craftsmanship, modern machinery, strict quality control, competitive factory pricing and on-time delivery.</p><Link className="textLink" to="/quality">Our quality approach <ArrowRight size={14}/></Link></motion.div><div className="principleGrid">{[['01','CRAFTSMANSHIP',Factory],['02','QUALITY CONTROL',CircleCheck],['03','CUSTOM PRODUCTION',Hammer],['04','GLOBAL DELIVERY',Truck]].map(([n,t,Icon])=><div key={n}><b>{n}</b><Icon size={18}/><strong>{t}</strong></div>)}</div></div></div></section>
</> }

function SectionIntro({eyebrow,title,copy,link,to}:{eyebrow:string,title:string,copy:string,link:string,to:string}){return <section className="intro"><div className="container introGrid"><div><div className="eyebrow">{eyebrow}</div><h2>{title}</h2></div><div><p>{copy}</p><Link className="textLink" to={to}>{link}<ArrowRight size={14}/></Link></div></div></section>}
function SectionHeader({eyebrow,title,link,to}:{eyebrow:string,title:string,link:string,to:string}){return <div className="sectionHeader"><div><div className="eyebrow">{eyebrow}</div><h2>{title}</h2></div><Link className="textLink" to={to}>{link}<ArrowRight size={14}/></Link></div>}
function CategoryCard({category,index}:{category:typeof categories[number],index:number}){const Icon=category.icon; return <motion.div className="categoryCard" initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:index*.05}}><Link to={`/products/${category.slug}`}><div className={`categoryArt art-${category.art}`}><img src={cloudinary(category.image)} alt={category.name}/><span>{String(index+1).padStart(2,'0')} / {category.prefix}</span><Icon size={22}/></div><div className="categoryInfo"><div><small>{category.count} PRODUCTS</small><h3>{category.name}</h3><p>Performance-focused B2B range.</p></div><ArrowRight size={18}/></div></Link></motion.div> }
function PageHero({eyebrow,title,copy,className='' }:{eyebrow:string,title:string,copy:string,className?:string}){return <section className={`pageHero ${className}`}><div className="container"><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{copy}</p></div></section>}
function Products(){const [params,setParams]=useSearchParams(); const active=params.get('category')||useParams().category||'all'; const filtered=active==='all'?products:products.filter(p=>p.category===active); return <><PageHero eyebrow="PRODUCT CATALOGUE" title="Performance gloves for serious buyers." copy="Browse the Skyline catalogue by application. Product photography is presented directly from the current Skyline asset library."/><section className="products section"><div className="container"><div className="filterBar"><button className={active==='all'?'selected':''} onClick={()=>setParams({})}>All Products <b>{products.length}</b></button>{categories.map(c=><button key={c.slug} className={active===c.slug?'selected':''} onClick={()=>setParams({category:c.slug})}>{c.name} <b>{c.count}</b></button>)}</div><div className="catalogMeta"><span>{filtered.length} products</span><span>SKU / APPLICATION / B2B</span></div><div className="productGrid">{filtered.map(p=><ProductCard key={p.slug} product={p}/>)}</div></div></section></> }
function ProductCard({product}:{product:Product}){return <Link className="productCard" to={`/products/${product.category}/${product.slug}`}><div className="productVisual"><img src={cloudinary(product.code)} alt={`${product.categoryName} ${product.index}`}/><span>{product.code}</span><i>VIEW</i></div><div className="productInfo"><small>{product.categoryName}</small><h3>{product.categoryName} {String(product.index).padStart(2,'0')}</h3><p>Request specification / quote</p></div></Link>}
function ProductDetail(){const {category,slug}=useParams(); const product=products.find(p=>p.slug===slug)||products.find(p=>p.category===category)||products[0]; return <><PageHero eyebrow={product.categoryName} title={`${product.categoryName} / ${String(product.index).padStart(2,'0')}`} copy="Detailed product presentation for B2B sourcing, private-label and wholesale enquiries."/><section className="section detail"><div className="container detailGrid"><div className="detailArt"><img src={cloudinary(product.code)} alt={product.categoryName}/><span>{product.code}</span></div><div><div className="eyebrow">PRODUCT SPECIFICATION</div><h2>{product.categoryName} {String(product.index).padStart(2,'0')}</h2><p>Built for application-specific performance, consistent production and scalable B2B supply.</p><div className="detailFacts"><div><b>SKU</b><span>{product.code}</span></div><div><b>CATEGORY</b><span>{product.categoryName}</span></div><div><b>SUPPLY</b><span>OEM / Private Label</span></div></div><Link className="quoteBtn" to="/contact">Request a Quote <ArrowRight size={15}/></Link></div></div></section></> }
function About(){return <><PageHero eyebrow="ABOUT SKYLINE" title="A Sialkot manufacturing partner built for global buyers." copy="Skyline Global Industries combines Sialkot glove-making expertise with a modern, export-focused approach to B2B supply."/><section className="section aboutFeature"><div className="container aboutGrid"><div><div className="eyebrow">FROM SIAlKOT TO GLOBAL MARKETS</div><h2>Craftsmanship meets disciplined production.</h2><p>Our positioning is straightforward: premium glove manufacturing, reliable communication, quality-focused production and flexible OEM/private-label support.</p><p>We serve brands, wholesalers, distributors and importers looking for a responsive manufacturing partner in Pakistan.</p></div><div className="aboutPhotoFrame"><img src={cloudinary('SLGI-FG-03')} alt="Skyline glove manufacturing"/></div></div></section></>}
function OEM(){return <><PageHero className="oemHero" eyebrow="OEM / PRIVATE LABEL" title="Your brand, engineered into the glove." copy="Develop, customize and scale products with Skyline through OEM and private-label production."/><section className="section oemPage"><div className="container oemPageGrid"><div><div className="eyebrow">CAPABILITY</div><h2>From concept to shipment.</h2><p>We support product selection, material and color direction, branding, packaging and production coordination for B2B buyers.</p><Link className="quoteBtn" to="/contact">Discuss your project <ArrowRight size={15}/></Link></div><div className="oemChecklist">{['Product development','Material / color customization','Branding & private label','Packaging coordination','Production & quality checks','Export-ready delivery'].map((x,i)=><div key={x}><span>{String(i+1).padStart(2,'0')}</span><strong>{x}</strong><ArrowRight size={15}/></div>)}</div></div></section></>}
function Manufacturing(){return <><PageHero eyebrow="MANUFACTURING" title="Production designed around consistency." copy="A practical manufacturing workflow focused on repeatable quality, scalable output and export readiness."/><section className="section manufacturingPage"><div className="container manufacturingGrid">{[['01','MATERIALS','Selected materials aligned to product application and buyer requirements.'],['02','CUTTING & ASSEMBLY','Controlled production stages for consistent fit and finish.'],['03','FINISHING','Branding, finishing and packaging preparation based on specification.'],['04','QUALITY CHECK','Inspection checkpoints before packing and shipment.'],['05','PACKING','Export-ready packing and labeling coordination.'],['06','DISPATCH','Shipment preparation for international B2B delivery.']].map(([n,t,c])=><article key={n}><b>{n}</b><h3>{t}</h3><p>{c}</p></article>)}</div></section></>}
function Quality(){return <><PageHero eyebrow="QUALITY" title="Quality control at every critical stage." copy="Our quality approach is built around inspection, consistency and clear buyer specifications."/><section className="section qualityGrid"><div className="container qualityInner"><div><div className="eyebrow">QUALITY SYSTEM</div><h2>Built to reduce surprises.</h2><p>We focus on specification alignment, material consistency, workmanship inspection and final checks before dispatch.</p></div><div className="qualityPoints">{['Specification confirmation','Material inspection','In-process checks','Final workmanship inspection','Packing verification','Pre-shipment readiness'].map((x,i)=><div key={x}><CircleCheck size={18}/><span>{x}</span><b>{String(i+1).padStart(2,'0')}</b></div>)}</div></div></section></>}
function Credentials(){return <><PageHero eyebrow="COMPANY CREDENTIALS" title="A clearer picture of who you are buying from." copy="Company information, manufacturing positioning and export-ready contact details for prospective B2B buyers."/><section className="section credentialsPage"><div className="container credentialGrid"><article><span>01</span><h3>Pakistan-based</h3><p>Manufacturing and export positioning from Sialkot, Punjab.</p></article><article><span>02</span><h3>B2B focused</h3><p>Serving brands, distributors, wholesalers and importers.</p></article><article><span>03</span><h3>OEM capable</h3><p>Private-label and custom production support.</p></article><article><span>04</span><h3>Direct enquiry</h3><p>Contact Skyline directly for specifications and quotations.</p></article></div></section></>}
function Gallery(){return <><PageHero eyebrow="GALLERY" title="See the product world behind the catalogue." copy="A visual selection of Skyline glove products and manufacturing-focused imagery."/><section className="section galleryPage"><div className="container"><div className="galleryTitle"><div><div className="eyebrow">SELECTED VISUALS</div><h2>Performance, detail, finish.</h2></div></div><div className="galleryGrid">{['SLGI-MG-03','SLGI-FG-04','SLGI-GG-05','SLGI-CG-05','SLGI-RAG-07','SLGI-TG-06'].map((code,i)=><div className="galleryArt" key={code}><img src={cloudinary(code)} alt={`Skyline gallery ${i+1}`}/><span>{String(i+1).padStart(2,'0')}</span></div>)}</div></div></section></>}
function Contact(){return <><PageHero eyebrow="CONTACT" title="Start a serious sourcing conversation." copy="Share your product, quantity, customization or OEM requirements and Skyline will respond with the next step."/><section className="section contactPage"><div className="container contactGrid"><div><div className="eyebrow">DIRECT CONTACT</div><h2>Let's discuss your requirement.</h2><div className="contactList"><a href={`tel:${contact.phone}`}>{contact.phone}</a><a href={`mailto:${contact.email}`}>{contact.email}</a><span>{contact.location}</span></div><a className="quoteBtn" href={whatsappUrl} target="_blank" rel="noopener noreferrer">Message on WhatsApp</a></div><form action={FORMSPREE_ENDPOINT} method="POST" className="contactForm"><label>Name<input name="name" required/></label><label>Company<input name="company"/></label><label>Email<input type="email" name="email" required/></label><label>Requirement<textarea name="message" rows={6} required/></label><button className="quoteBtn" type="submit">Send Enquiry <ArrowRight size={15}/></button></form></div></section></>}
function NotFound(){return <><PageHero eyebrow="404" title="This page does not exist." copy="Return to the Skyline catalogue or contact the team directly."/><section className="section"><div className="container"><Link className="quoteBtn" to="/products">Back to catalogue <ArrowRight size={15}/></Link></div></section></>}
