import { useMemo, useState, useEffect } from 'react';
import { Link, NavLink, Route, Routes, useParams, useSearchParams } from 'react-router-dom';
import { AnimatePresence, motion, useReducedMotion } from 'framer-motion';
import { ArrowDownRight, ArrowRight, Bike, Box, Check, ChevronRight, CircleCheck, Factory, FileCheck2, Globe2, Hammer, Mail, Menu, MessageCircle, Package, PenTool, ShieldCheck, Sparkles, Truck, Users, X } from 'lucide-react';

const contact = { phone: '+92 342 7189884', email: 'skylineglobalindustries@gmail.com', location: 'Sialkot, Punjab, Pakistan' };
const cloudinary = (code: string) => `https://res.cloudinary.com/m2w7btvw/image/upload/f_auto,q_auto/${code}`;

const categories = [
  { slug: 'motorbike-gloves', name: 'MotorBike Gloves', prefix: 'SLGI-MG', count: 12, icon: Bike, art: 'motorbike', image: 'SLGI-MG-01' },
  { slug: 'rugby-gloves', name: 'Rugby Gloves', prefix: 'SLGI-RAG', count: 8, icon: ShieldCheck, art: 'rugby', image: 'SLGI-RAG-01' },
  { slug: 'golf-gloves', name: 'Golf Gloves', prefix: 'SLGI-GG', count: 8, icon: Sparkles, art: 'golf', image: 'SLGI-GG-01' },
  { slug: 'fitness-gloves', name: 'Fitness Gloves', prefix: 'SLGI-FG', count: 8, icon: Hammer, art: 'fitness', image: 'SLGI-FG-01' },
  { slug: 'cycling-gloves', name: 'Cycling Gloves', prefix: 'SLGI-CG', count: 8, icon: Bike, art: 'cycling', image: 'SLGI-CG-01' },
  { slug: 'tactical-gloves', name: 'Tactical Gloves', prefix: 'SLGI-TG', count: 8, icon: ShieldCheck, art: 'tactical', image: 'SLGI-TG-01' },
] as const;

type Product = { slug: string; code: string; category: string; categoryName: string; index: number };
const products: Product[] = categories.flatMap((category) => Array.from({ length: category.count }, (_, index) => ({
  slug: `${category.slug}-${String(index + 1).padStart(2, '0')}`,
  code: `${category.prefix}-${String(index + 1).padStart(2, '0')}`,
  category: category.slug,
  categoryName: category.name,
  index: index + 1,
})));

const nav = [['/about', 'About'], ['/products', 'Products'], ['/oem-private-label', 'OEM / Private Label'], ['/manufacturing', 'Manufacturing'], ['/quality', 'Quality'], ['/gallery', 'Gallery'], ['/contact', 'Contact']];
const reveal = { hidden: { opacity: 0, y: 28 }, show: { opacity: 1, y: 0, transition: { duration: .65, ease: [0.22, 1, .36, 1] } } };

export default function App() {
  return <SiteShell><AnimatePresence mode="wait"><Routes>
    <Route path="/" element={<Home />} /><Route path="/about" element={<About />} /><Route path="/products" element={<Products />} />
    <Route path="/products/:category" element={<Products />} /><Route path="/products/:category/:slug" element={<ProductDetail />} />
    <Route path="/oem-private-label" element={<OEM />} /><Route path="/manufacturing" element={<Manufacturing />} /><Route path="/quality" element={<Quality />} />
    <Route path="/credentials" element={<Credentials />} /><Route path="/gallery" element={<Gallery />} /><Route path="/contact" element={<Contact />} /><Route path="*" element={<NotFound />} />
  </Routes></AnimatePresence></SiteShell>;
}

function SiteShell({ children }: { children: React.ReactNode }) {
  const [open, setOpen] = useState(false);
  return <div className="site"><header className="header"><div className="container nav">
    <Link className="brand" to="/" onClick={() => setOpen(false)}><img src="/images/logo.svg" alt="Skyline Global Industries" /><span><strong>SKYLINE</strong><small>GLOBAL INDUSTRIES</small></span></Link>
    <nav className="desktopNav">{nav.map(([href, label]) => <NavLink key={href} to={href}>{label}</NavLink>)}</nav>
    <Link className="quoteBtn navQuote" to="/contact">Request a Quote <ArrowRight size={15}/></Link>
    <button className="menuBtn" onClick={() => setOpen(v => !v)} aria-label="Menu">{open ? <X/> : <Menu/>}</button>
  </div>{open && <motion.nav className="mobileNav" initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}}>{nav.map(([href,label]) => <Link key={href} to={href} onClick={() => setOpen(false)}>{label}</Link>)}<Link className="quoteBtn" to="/contact" onClick={() => setOpen(false)}>Request a Quote <ArrowRight size={15}/></Link></motion.nav>}</header><main>{children}</main><Footer/></div>;
}

function Footer(){ return <footer className="footer"><div className="container footerGrid"><div><img className="footerLogo" src="/images/logo.svg" alt="Skyline Global Industries"/><p>Manufacturers and exporters of premium quality gloves from Sialkot, Pakistan.</p></div><div><span>EXPLORE</span><Link to="/products">Product Catalogue</Link><Link to="/oem-private-label">OEM / Private Label</Link><Link to="/manufacturing">Manufacturing</Link><Link to="/quality">Quality</Link></div><div><span>COMPANY</span><Link to="/about">About Skyline</Link><Link to="/credentials">Company Credentials</Link><Link to="/gallery">Gallery</Link><Link to="/contact">Contact</Link></div><div><span>CONTACT</span><a href={`tel:${contact.phone}`}>{contact.phone}</a><a href={`mailto:${contact.email}`}>{contact.email}</a><small>{contact.location}</small></div></div><div className="container footerBottom"><span>© 2026 Skyline Global Industries</span><span>Sialkot · Pakistan</span></div></footer> }

function Home(){ const reduce=useReducedMotion(); return <>
  <section className="heroCatalog"><div className="heroBlob one"/><div className="heroBlob two"/><div className="container heroCatalogGrid">
    <motion.div className="heroCatalogCopy" variants={reveal} initial="hidden" animate="show"><div className="eyebrow">SIALKOT · PAKISTAN</div><h1>MANUFACTURERS &<br/>EXPORTERS OF<br/><em>PREMIUM QUALITY</em><br/><strong>GLOVES</strong></h1><p>OEM, private-label and custom glove manufacturing for brands, wholesalers, distributors and importers.</p><div className="heroActions"><Link className="quoteBtn" to="/products">Explore Catalogue <ArrowRight size={16}/></Link><Link className="outlineBtn" to="/contact">Start an Enquiry</Link></div><div className="contactStrip"><a href={`tel:${contact.phone}`}><MessageCircle size={16}/>{contact.phone}</a><a href={`mailto:${contact.email}`}><Mail size={16}/>{contact.email}</a><span><Globe2 size={16}/>{contact.location}</span></div></motion.div>
    <motion.div className="heroCatalogArt" initial={reduce?false:{opacity:0,scale:.88,x:30}} animate={reduce?undefined:{opacity:1,scale:1,x:0}} transition={{duration:1,ease:[.16,1,.3,1]}}><div className="worldDisc"/><div className="heroProductCollage">{['SLGI-MG-01','SLGI-GG-01','SLGI-TG-01','SLGI-FG-01','SLGI-RAG-01'].map((code,i)=><img key={code} className={`heroProduct p${i+1}`} src={cloudinary(code)} alt="Skyline premium glove" />)}</div><div className="heroTag">SKYLINE / 01</div></motion.div>
  </div><div className="catalogCurve"><span>OEM & PRIVATE LABEL</span><span>QUALITY CONTROL</span><span>GLOBAL B2B SUPPLY</span><Link to="/about">DISCOVER SKYLINE <ArrowDownRight size={14}/></Link></div></section>
  <SectionIntro eyebrow="THE SKYLINE APPROACH" title="Built in Sialkot. Ready for global buyers." copy="Skyline Global Industries is positioned as a glove manufacturing and export partner focused on craftsmanship, modern production, quality control and dependable B2B service." link="About the company" to="/about"/>
  <section className="section catalogSection"><div className="container"><SectionHeader eyebrow="PRODUCT COLLECTION" title="Six focused glove categories." link="View full catalogue" to="/products"/><div className="categoryGrid">{categories.map((c,i)=><CategoryCard key={c.slug} category={c} index={i}/>)}</div></div></section>
  <section className="oemBand"><div className="container oemBandGrid"><div><div className="eyebrow light">OEM & PRIVATE LABEL</div><h2>Your brand.<br/><em>Our manufacturing.</em></h2><p>From product development to final packaging, we provide complete OEM and private-label support tailored to your brand.</p><Link className="lightBtn" to="/oem-private-label">Explore OEM capabilities <ArrowRight size={16}/></Link></div><div className="oemRealVisual"><img className="oemProductPhoto" src={cloudinary('SLGI-TG-01')} alt="Skyline tactical glove"/><div className="oemPackageMock">YOUR<br/>BRAND<br/><Box size={34}/></div></div></div></section>
  <section className="section commitment"><div className="container"><div className="commitGrid"><motion.div variants={reveal} initial="hidden" whileInView="show" viewport={{once:true}}><div className="eyebrow">WHY BUYERS WORK WITH US</div><h2>Quality is built into the process.</h2><p>Our company material emphasizes skilled craftsmanship, modern machinery, strict quality control, competitive factory pricing and on-time delivery.</p><Link className="textLink" to="/quality">Our quality approach <ArrowRight size={15}/></Link></motion.div><div className="principleGrid">{[['01',Factory,'Skilled craftsmanship'],['02',ShieldCheck,'Quality control'],['03',Truck,'On-time delivery'],['04',Globe2,'Global B2B focus']].map(([n,I,t])=><motion.div key={n as string} variants={reveal} initial="hidden" whileInView="show" viewport={{once:true}}><b>{n as string}</b><I size={22}/><strong>{t as string}</strong></motion.div>)}</div></div></div></section>
  <CTA/>
</> }

function SectionIntro({eyebrow,title,copy,link,to}:{eyebrow:string;title:string;copy:string;link:string;to:string}){return <section className="section intro"><div className="container introGrid"><div><div className="eyebrow">{eyebrow}</div><h2>{title}</h2></div><div><p>{copy}</p><Link className="textLink" to={to}>{link}<ArrowRight size={15}/></Link></div></div></section>}
function SectionHeader({eyebrow,title,link,to}:{eyebrow:string;title:string;link:string;to:string}){return <div className="sectionHeader"><div><div className="eyebrow">{eyebrow}</div><h2>{title}</h2></div><Link className="textLink" to={to}>{link}<ArrowRight size={15}/></Link></div>}
function CategoryCard({category,index}:{category:(typeof categories)[number];index:number}){const Icon=category.icon;return <Link className="categoryCard" to={`/products/${category.slug}`}><div className={`categoryArt art-${category.art}`}><img src={cloudinary(category.image)} alt={category.name}/><div className="artRing"/><Icon size={28}/><span>0{index+1}</span></div><div className="categoryInfo"><div><small>{category.prefix}</small><h3>{category.name}</h3><p>Confirmed catalogue category for B2B sourcing.</p></div><ArrowRight size={18}/></div></Link>}
function PageHero({eyebrow,title,copy}:{eyebrow:string;title:string;copy?:string}){return <section className="pageHero"><div className="container"><div className="eyebrow">{eyebrow}</div><h1>{title}</h1>{copy&&<p>{copy}</p>}</div></section>}

function Products(){const {category}=useParams(); const [filter,setFilter]=useState(category??'all'); useEffect(()=>{setFilter(category??'all')},[category]); const visible=useMemo(()=>filter==='all'?products:products.filter(p=>p.category===filter),[filter]);return <><PageHero eyebrow="PRODUCT CATALOGUE" title="A visual range built for faster sourcing." copy="Browse the confirmed launch categories and SKU references. Technical specifications are only shown where supplied by the source catalogue."/><section className="section products"><div className="container"><div className="filterBar"><button className={filter==='all'?'selected':''} onClick={()=>setFilter('all')}>All <b>{products.length}</b></button>{categories.map(c=><button key={c.slug} className={filter===c.slug?'selected':''} onClick={()=>setFilter(c.slug)}>{c.name}</button>)}</div><div className="catalogMeta"><span>{visible.length} references</span><span>SKU-led · OEM enquiries welcome</span></div><div className="productGrid">{visible.map((p,i)=><ProductCard key={p.slug} product={p} index={i}/>)}</div></div></section></>}
function ProductCard({product,index}:{product:Product;index:number}){return <motion.div initial={{opacity:0,y:18}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{duration:.4,delay:Math.min(index*.02,.12)}}><Link className="productCard" to={`/products/${product.category}/${product.slug}`}><div className="productVisual"><img src={cloudinary(product.code)} alt={product.code}/><span>{product.code}</span><i>VIEW <ChevronRight size={12}/></i></div><div className="productMeta"><small>{product.categoryName}</small><strong>{product.code}</strong><ArrowRight size={16}/></div></Link></motion.div>}
function ProductDetail(){const {category,slug}=useParams();const product=products.find(p=>p.category===category&&p.slug===slug);if(!product)return <NotFound/>;return <><PageHero eyebrow={product.categoryName.toUpperCase()} title={product.code} copy="Product reference from the confirmed launch catalogue."/><section className="section detail"><div className="container detailGrid"><div className="detailArt"><img src={cloudinary(product.code)} alt={product.code}/></div><div><div className="eyebrow">PRODUCT REFERENCE</div><h2>{product.code}</h2><div className="detailRows"><div><span>Category</span><b>{product.categoryName}</b></div><div><span>Product code</span><b>{product.code}</b></div><div><span>Supply model</span><b>OEM / B2B</b></div></div><p className="sourceNote">Materials, sizes, colours, applications and individual MOQ are not published because they were not supplied in the source catalogue.</p><Link className="quoteBtn" to={`/contact?product=${encodeURIComponent(product.code)}`}>Request a Quote <ArrowRight size={16}/></Link></div></div></section></>}

function About(){return <><PageHero eyebrow="ABOUT SKYLINE" title="A Sialkot manufacturing partner built for global business." copy="Skyline Global Industries manufactures and exports premium-quality gloves, with a focus on OEM manufacturing, private labeling and custom glove solutions."/><section className="section aboutFeature"><div className="container aboutGrid"><div className="aboutVisual"><div className="aboutCircle"/><div className="aboutPhotoFrame"><img src={cloudinary('SLGI-FG-01')} alt="Skyline glove manufacturing product"/></div><span>SIALKOT / PAKISTAN</span></div><div><div className="eyebrow">WHO WE ARE</div><h2>Manufacturing with a buyer-first mindset.</h2><p>Based in Sialkot, Pakistan, Skyline serves brands, wholesalers, distributors and importers looking for a dependable glove manufacturing partner.</p><p>The supplied company material positions the business around skilled craftsmanship, modern production technology, strict quality control, competitive factory pricing and on-time delivery.</p><div className="points"><div><CircleCheck size={19}/><span>Skilled craftsmanship</span></div><div><CircleCheck size={19}/><span>Modern production technology</span></div><div><CircleCheck size={19}/><span>Strict quality control</span></div><div><CircleCheck size={19}/><span>Dependable B2B service</span></div></div></div></div></section><CTA/></>}

function OEM(){const services=[['01',PenTool,'Custom Glove Design'],['02',Sparkles,'Custom Logo Printing'],['03',Users,'Private Label Branding'],['04',Package,'Custom Packaging'],['05',ShieldCheck,'Premium Quality Materials'],['06',Truck,'Fast Sampling & Production']];return <><PageHero eyebrow="OEM & PRIVATE LABEL" title="Your design. Your logo. Your package." copy="Complete OEM and private-label manufacturing support for brands, wholesalers, distributors and importers."/><section className="section oemPage"><div className="container oemPageGrid"><div><div className="eyebrow">OUR SERVICES</div><h2>From product development to final packaging.</h2><p>We provide complete OEM and private-label glove manufacturing solutions tailored to your brand.</p><div className="serviceList">{services.map(([n,I,t])=><div key={n as string}><b>{n as string}</b><I size={21}/><span>{t as string}</span></div>)}</div></div><div className="oemRealVisual"><img className="oemProductPhoto" src={cloudinary('SLGI-TG-01')} alt="Skyline tactical glove"/><div className="oemPackageMock">YOUR<br/>LOGO<br/><span>PRIVATE LABEL</span></div></div></div></section><CTA/></>}

function Manufacturing(){return <><PageHero eyebrow="MANUFACTURING" title="Skilled production. Consistent execution." copy="A manufacturing story centered on Sialkot craftsmanship, modern machinery and dependable B2B production support."/><section className="section process"><div className="container"><div className="processGrid">{[['01','Design & development','Translate the buyer brief into a production-ready glove program.'],['02','Sampling','Move from concept to sample before production.'],['03','Production','Coordinate skilled manufacturing around the confirmed specification.'],['04','Quality control','Maintain quality checks throughout the production workflow.'],['05','Packing & dispatch','Prepare finished orders for dependable export handling.']].map(([n,t,c])=><motion.div key={n} variants={reveal} initial="hidden" whileInView="show" viewport={{once:true}}><span>{n}</span><h3>{t}</h3><p>{c}</p><ArrowRight size={18}/></motion.div>)}</div></div></section><CTA/></>}

function Quality(){return <><PageHero eyebrow="QUALITY" title="Quality is a process, not a badge." copy="The company positioning emphasizes quality control, innovation, customer satisfaction and long-term reliability."/><section className="section qualityPage"><div className="container qualityGrid"><div><div className="eyebrow">QUALITY COMMITMENT</div><h2>Built around repeatable control.</h2><p>Skyline's supplied material highlights strict quality control and customer satisfaction as core parts of its manufacturing proposition.</p></div><div className="qualityCards">{[['01','Material & construction checks'],['02','Production-stage inspection'],['03','Finished-goods review'],['04','Buyer-focused consistency']].map(([n,t])=><div key={n}><b>{n}</b><ShieldCheck size={21}/><strong>{t}</strong></div>)}</div></div></section><CTA/></>}

function Credentials(){return <><PageHero eyebrow="COMPANY CREDENTIALS" title="Corporate registration, clearly presented." copy="Official company documentation supplied for the website."/><section className="section credentials"><div className="container"><div className="credentialCard"><div className="credentialIcon"><FileCheck2 size={30}/></div><div><span>LEGAL REGISTRATION</span><h2>Certificate of Incorporation</h2><p>Skyline Global Industries (SMC-Private) Limited is incorporated under the Companies Act, 2017.</p><div className="credentialMeta"><span>Corporate Unique Identification No.</span><strong>0323878</strong></div></div><div className="credentialSeal">SECP<br/><small>VERIFIABLE</small></div></div></div></section></>}

function Gallery(){return <><PageHero eyebrow="GALLERY" title="A visual catalogue of the Skyline range." copy="Explore the confirmed glove categories and manufacturing presentation."/><section className="section gallery"><div className="container"><div className="galleryTitle"><div><div className="eyebrow">VISUAL CATALOGUE</div><h2>Built to be seen.<br/>Ready to be sourced.</h2></div><p>A curated view of the glove range, product presentation and brand direction.</p></div><div className="galleryGrid">{categories.map((c,i)=><motion.div key={c.slug} className="galleryTile" whileHover={{y:-7}}><div className={`galleryArt art-${c.art}`}><img src={cloudinary(c.image)} alt={c.name}/><span>0{i+1}</span><c.icon size={30}/></div><div><small>{c.prefix}</small><h3>{c.name}</h3><ArrowRight size={16}/></div></motion.div>)}</div></div></section></>}

function Contact(){const [params]=useSearchParams();return <><PageHero eyebrow="CONTACT" title="Let's build your next glove program." copy="Share the category, quantity and private-label requirements you have in mind."/><section className="section contactPage"><div className="container contactGrid"><div><div className="eyebrow">START AN ENQUIRY</div><h2>Tell us what you need.</h2><div className="contactCards"><a href={`tel:${contact.phone}`}><MessageCircle/><span>Phone / WhatsApp<br/><b>{contact.phone}</b></span></a><a href={`mailto:${contact.email}`}><Mail/><span>Email<br/><b>{contact.email}</b></span></a><div><Globe2/><span>Location<br/><b>{contact.location}</b></span></div></div></div><form className="quoteForm" onSubmit={e=>e.preventDefault()}><label>Name<input placeholder="Your name"/></label><label>Business / Brand<input placeholder="Company name"/></label><label>Email<input type="email" placeholder="you@company.com"/></label><label>Product / Category<input defaultValue={params.get('product')??''} placeholder="e.g. MotorBike Gloves"/></label><label>Message<textarea rows={5} placeholder="Tell us about quantity, branding, packaging or target market."/></label><button className="quoteBtn" type="submit">Send Enquiry <ArrowRight size={16}/></button></form></div></section></>}
function CTA(){return <section className="cta"><div className="container ctaInner"><div><div className="eyebrow">START A CONVERSATION</div><h2>Have a glove program in mind?</h2><p>Let's turn your sourcing brief into a clear next step.</p></div><Link className="quoteBtn large" to="/contact">Request a Quote <ArrowRight size={17}/></Link></div></section>}
function NotFound(){return <><PageHero eyebrow="404" title="This page isn't in the catalogue."/><section className="section"><div className="container"><Link className="quoteBtn" to="/">Back to Home <ArrowRight size={16}/></Link></div></section></>}
